trigger:
  - none
  # - master

pool:
  name: Default

steps:
  - bash: dotnet restore
    displayName: "dotnet restore"

  - task: DotNetCoreCLI@2
    displayName: "Publish Api Code"
    inputs:
      command: publish
      workingDirectory: Api
      arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
      publishWebProjects: False
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy Api"
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "My Azure Service connection"
      appType: "webAppLinux"
      WebAppName: "tzather-test-mock-cs"
      packageForLinux: "$(Build.ArtifactStagingDirectory)/a.zip"
